// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.11.3
// source: examples/geo/proto/features.proto

package proto

import (
	_ "github.com/bitcdr/protovalid/valid"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Size.
type Features_PoiFeature_Marker_Size int32

const (
	Features_PoiFeature_Marker_SIZE_UNSPECIFIED Features_PoiFeature_Marker_Size = 0
	Features_PoiFeature_Marker_SIZE_SMALL       Features_PoiFeature_Marker_Size = 1
	Features_PoiFeature_Marker_SIZE_MEDIUM      Features_PoiFeature_Marker_Size = 2
	Features_PoiFeature_Marker_SIZE_LARGE       Features_PoiFeature_Marker_Size = 3
)

// Enum value maps for Features_PoiFeature_Marker_Size.
var (
	Features_PoiFeature_Marker_Size_name = map[int32]string{
		0: "SIZE_UNSPECIFIED",
		1: "SIZE_SMALL",
		2: "SIZE_MEDIUM",
		3: "SIZE_LARGE",
	}
	Features_PoiFeature_Marker_Size_value = map[string]int32{
		"SIZE_UNSPECIFIED": 0,
		"SIZE_SMALL":       1,
		"SIZE_MEDIUM":      2,
		"SIZE_LARGE":       3,
	}
)

func (x Features_PoiFeature_Marker_Size) Enum() *Features_PoiFeature_Marker_Size {
	p := new(Features_PoiFeature_Marker_Size)
	*p = x
	return p
}

func (x Features_PoiFeature_Marker_Size) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Features_PoiFeature_Marker_Size) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_geo_proto_features_proto_enumTypes[0].Descriptor()
}

func (Features_PoiFeature_Marker_Size) Type() protoreflect.EnumType {
	return &file_examples_geo_proto_features_proto_enumTypes[0]
}

func (x Features_PoiFeature_Marker_Size) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Features_PoiFeature_Marker_Size.Descriptor instead.
func (Features_PoiFeature_Marker_Size) EnumDescriptor() ([]byte, []int) {
	return file_examples_geo_proto_features_proto_rawDescGZIP(), []int{0, 1, 0, 0}
}

type Features struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Points of Interest (POI).
	Pois []*Features_PoiFeature `protobuf:"bytes,1,rep,name=pois,proto3" json:"pois,omitempty"`
	// Tracks.
	Tracks []*Features_TrackFeature `protobuf:"bytes,2,rep,name=tracks,proto3" json:"tracks,omitempty"`
}

func (x *Features) Reset() {
	*x = Features{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examples_geo_proto_features_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Features) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Features) ProtoMessage() {}

func (x *Features) ProtoReflect() protoreflect.Message {
	mi := &file_examples_geo_proto_features_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Features.ProtoReflect.Descriptor instead.
func (*Features) Descriptor() ([]byte, []int) {
	return file_examples_geo_proto_features_proto_rawDescGZIP(), []int{0}
}

func (x *Features) GetPois() []*Features_PoiFeature {
	if x != nil {
		return x.Pois
	}
	return nil
}

func (x *Features) GetTracks() []*Features_TrackFeature {
	if x != nil {
		return x.Tracks
	}
	return nil
}

// Geographic coordinate in WGS84 reference system.
type Features_Coordinate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Longitude.
	Longitude float64 `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// Latitude.
	Latitude float64 `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
}

func (x *Features_Coordinate) Reset() {
	*x = Features_Coordinate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examples_geo_proto_features_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Features_Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Features_Coordinate) ProtoMessage() {}

func (x *Features_Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_examples_geo_proto_features_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Features_Coordinate.ProtoReflect.Descriptor instead.
func (*Features_Coordinate) Descriptor() ([]byte, []int) {
	return file_examples_geo_proto_features_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Features_Coordinate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Features_Coordinate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

// Point of Interest feature with point geometry.
type Features_PoiFeature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Foreign names.
	ForeignNames []string `protobuf:"bytes,2,rep,name=foreign_names,json=foreignNames,proto3" json:"foreign_names,omitempty"`
	// Geographic coordinate in WGS84 reference system.
	Coordinate *Features_Coordinate `protobuf:"bytes,3,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	// Marker.
	Marker *Features_PoiFeature_Marker `protobuf:"bytes,4,opt,name=marker,proto3" json:"marker,omitempty"`
}

func (x *Features_PoiFeature) Reset() {
	*x = Features_PoiFeature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examples_geo_proto_features_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Features_PoiFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Features_PoiFeature) ProtoMessage() {}

func (x *Features_PoiFeature) ProtoReflect() protoreflect.Message {
	mi := &file_examples_geo_proto_features_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Features_PoiFeature.ProtoReflect.Descriptor instead.
func (*Features_PoiFeature) Descriptor() ([]byte, []int) {
	return file_examples_geo_proto_features_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Features_PoiFeature) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Features_PoiFeature) GetForeignNames() []string {
	if x != nil {
		return x.ForeignNames
	}
	return nil
}

func (x *Features_PoiFeature) GetCoordinate() *Features_Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *Features_PoiFeature) GetMarker() *Features_PoiFeature_Marker {
	if x != nil {
		return x.Marker
	}
	return nil
}

type Features_TrackFeature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Geographic coordinates in WGS84 reference system.
	Coordinates []*Features_Coordinate `protobuf:"bytes,2,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	// Stroke.
	Stroke *Features_TrackFeature_Stroke `protobuf:"bytes,3,opt,name=stroke,proto3" json:"stroke,omitempty"`
}

func (x *Features_TrackFeature) Reset() {
	*x = Features_TrackFeature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examples_geo_proto_features_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Features_TrackFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Features_TrackFeature) ProtoMessage() {}

func (x *Features_TrackFeature) ProtoReflect() protoreflect.Message {
	mi := &file_examples_geo_proto_features_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Features_TrackFeature.ProtoReflect.Descriptor instead.
func (*Features_TrackFeature) Descriptor() ([]byte, []int) {
	return file_examples_geo_proto_features_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Features_TrackFeature) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Features_TrackFeature) GetCoordinates() []*Features_Coordinate {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *Features_TrackFeature) GetStroke() *Features_TrackFeature_Stroke {
	if x != nil {
		return x.Stroke
	}
	return nil
}

// Marker.
type Features_PoiFeature_Marker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Color as RGB in hex.
	Color string `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	// Size.
	Size Features_PoiFeature_Marker_Size `protobuf:"varint,2,opt,name=size,proto3,enum=examples.geo.proto.Features_PoiFeature_Marker_Size" json:"size,omitempty"`
}

func (x *Features_PoiFeature_Marker) Reset() {
	*x = Features_PoiFeature_Marker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examples_geo_proto_features_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Features_PoiFeature_Marker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Features_PoiFeature_Marker) ProtoMessage() {}

func (x *Features_PoiFeature_Marker) ProtoReflect() protoreflect.Message {
	mi := &file_examples_geo_proto_features_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Features_PoiFeature_Marker.ProtoReflect.Descriptor instead.
func (*Features_PoiFeature_Marker) Descriptor() ([]byte, []int) {
	return file_examples_geo_proto_features_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *Features_PoiFeature_Marker) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Features_PoiFeature_Marker) GetSize() Features_PoiFeature_Marker_Size {
	if x != nil {
		return x.Size
	}
	return Features_PoiFeature_Marker_SIZE_UNSPECIFIED
}

// Stroke.
type Features_TrackFeature_Stroke struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Color as RGB in hex.
	Color string `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	// Width.
	Width int32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
}

func (x *Features_TrackFeature_Stroke) Reset() {
	*x = Features_TrackFeature_Stroke{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examples_geo_proto_features_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Features_TrackFeature_Stroke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Features_TrackFeature_Stroke) ProtoMessage() {}

func (x *Features_TrackFeature_Stroke) ProtoReflect() protoreflect.Message {
	mi := &file_examples_geo_proto_features_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Features_TrackFeature_Stroke.ProtoReflect.Descriptor instead.
func (*Features_TrackFeature_Stroke) Descriptor() ([]byte, []int) {
	return file_examples_geo_proto_features_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *Features_TrackFeature_Stroke) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Features_TrackFeature_Stroke) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

var File_examples_geo_proto_features_proto protoreflect.FileDescriptor

var file_examples_geo_proto_features_proto_rawDesc = []byte{
	0x0a, 0x21, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x67, 0x65, 0x6f, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x12, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x67, 0x65,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x2f, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf4, 0x07, 0x0a, 0x08, 0x46,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x3b, 0x0a, 0x04, 0x70, 0x6f, 0x69, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73,
	0x2e, 0x67, 0x65, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x73, 0x2e, 0x50, 0x6f, 0x69, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x04,
	0x70, 0x6f, 0x69, 0x73, 0x12, 0x41, 0x0a, 0x06, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e,
	0x67, 0x65, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x06, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x1a, 0x7e, 0x0a, 0x0a, 0x43, 0x6f, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x61, 0x74, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x42, 0x1a, 0x82, 0xb5, 0x18, 0x16, 0x0a, 0x14,
	0x09, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x66, 0xc0, 0x21, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80,
	0x66, 0x40, 0x38, 0x04, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12,
	0x36, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x42, 0x1a, 0x82, 0xb5, 0x18, 0x16, 0x0a, 0x14, 0x09, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80,
	0x56, 0xc0, 0x19, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x56, 0x40, 0x38, 0x04, 0x52, 0x08, 0x6c,
	0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x1a, 0xbe, 0x03, 0x0a, 0x0a, 0x50, 0x6f, 0x69, 0x46,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x82, 0xb5, 0x18, 0x06, 0x72, 0x04, 0x10, 0x01, 0x48, 0x03,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x6f, 0x72, 0x65, 0x69, 0x67,
	0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x66,
	0x6f, 0x72, 0x65, 0x69, 0x67, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x47, 0x0a, 0x0a, 0x63,
	0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x27, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x67, 0x65, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x43, 0x6f,
	0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x0a, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69,
	0x6e, 0x61, 0x74, 0x65, 0x12, 0x46, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e,
	0x67, 0x65, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x73, 0x2e, 0x50, 0x6f, 0x69, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x4d, 0x61,
	0x72, 0x6b, 0x65, 0x72, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x1a, 0xd9, 0x01, 0x0a,
	0x06, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x16, 0x82, 0xb5, 0x18, 0x12, 0x72, 0x10, 0x3a, 0x0e,
	0x5e, 0x23, 0x5b, 0x30, 0x2d, 0x39, 0x61, 0x2d, 0x66, 0x5d, 0x7b, 0x36, 0x7d, 0x24, 0x52, 0x05,
	0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x52, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x33, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x67,
	0x65, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x2e, 0x50, 0x6f, 0x69, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x4d, 0x61, 0x72,
	0x6b, 0x65, 0x72, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x42, 0x09, 0x82, 0xb5, 0x18, 0x05, 0x92, 0x01,
	0x02, 0x08, 0x01, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x4d, 0x0a, 0x04, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x49, 0x5a, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x49, 0x5a, 0x45, 0x5f,
	0x53, 0x4d, 0x41, 0x4c, 0x4c, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x49, 0x5a, 0x45, 0x5f,
	0x4d, 0x45, 0x44, 0x49, 0x55, 0x4d, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x49, 0x5a, 0x45,
	0x5f, 0x4c, 0x41, 0x52, 0x47, 0x45, 0x10, 0x03, 0x1a, 0xa6, 0x02, 0x0a, 0x0c, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x08, 0x82, 0xb5, 0x18, 0x04, 0x72, 0x02, 0x10,
	0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x54, 0x0a, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x67, 0x65, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x61, 0x74, 0x65, 0x42, 0x09, 0x82, 0xb5, 0x18, 0x05, 0x82, 0x01, 0x02, 0x18, 0x02,
	0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x12, 0x48, 0x0a,
	0x06, 0x73, 0x74, 0x72, 0x6f, 0x6b, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x67, 0x65, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x6f, 0x6b, 0x65, 0x52,
	0x06, 0x73, 0x74, 0x72, 0x6f, 0x6b, 0x65, 0x1a, 0x58, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x6f, 0x6b,
	0x65, 0x12, 0x2c, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x16, 0x82, 0xb5, 0x18, 0x12, 0x72, 0x10, 0x3a, 0x0e, 0x5e, 0x23, 0x5b, 0x30, 0x2d, 0x39,
	0x61, 0x2d, 0x66, 0x5d, 0x7b, 0x36, 0x7d, 0x24, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12,
	0x20, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a,
	0x82, 0xb5, 0x18, 0x06, 0x1a, 0x04, 0x08, 0x01, 0x18, 0x0a, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74,
	0x68, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x62, 0x69, 0x74, 0x63, 0x64, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x67, 0x65, 0x6f, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_examples_geo_proto_features_proto_rawDescOnce sync.Once
	file_examples_geo_proto_features_proto_rawDescData = file_examples_geo_proto_features_proto_rawDesc
)

func file_examples_geo_proto_features_proto_rawDescGZIP() []byte {
	file_examples_geo_proto_features_proto_rawDescOnce.Do(func() {
		file_examples_geo_proto_features_proto_rawDescData = protoimpl.X.CompressGZIP(file_examples_geo_proto_features_proto_rawDescData)
	})
	return file_examples_geo_proto_features_proto_rawDescData
}

var file_examples_geo_proto_features_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_examples_geo_proto_features_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_examples_geo_proto_features_proto_goTypes = []interface{}{
	(Features_PoiFeature_Marker_Size)(0), // 0: examples.geo.proto.Features.PoiFeature.Marker.Size
	(*Features)(nil),                     // 1: examples.geo.proto.Features
	(*Features_Coordinate)(nil),          // 2: examples.geo.proto.Features.Coordinate
	(*Features_PoiFeature)(nil),          // 3: examples.geo.proto.Features.PoiFeature
	(*Features_TrackFeature)(nil),        // 4: examples.geo.proto.Features.TrackFeature
	(*Features_PoiFeature_Marker)(nil),   // 5: examples.geo.proto.Features.PoiFeature.Marker
	(*Features_TrackFeature_Stroke)(nil), // 6: examples.geo.proto.Features.TrackFeature.Stroke
}
var file_examples_geo_proto_features_proto_depIdxs = []int32{
	3, // 0: examples.geo.proto.Features.pois:type_name -> examples.geo.proto.Features.PoiFeature
	4, // 1: examples.geo.proto.Features.tracks:type_name -> examples.geo.proto.Features.TrackFeature
	2, // 2: examples.geo.proto.Features.PoiFeature.coordinate:type_name -> examples.geo.proto.Features.Coordinate
	5, // 3: examples.geo.proto.Features.PoiFeature.marker:type_name -> examples.geo.proto.Features.PoiFeature.Marker
	2, // 4: examples.geo.proto.Features.TrackFeature.coordinates:type_name -> examples.geo.proto.Features.Coordinate
	6, // 5: examples.geo.proto.Features.TrackFeature.stroke:type_name -> examples.geo.proto.Features.TrackFeature.Stroke
	0, // 6: examples.geo.proto.Features.PoiFeature.Marker.size:type_name -> examples.geo.proto.Features.PoiFeature.Marker.Size
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_examples_geo_proto_features_proto_init() }
func file_examples_geo_proto_features_proto_init() {
	if File_examples_geo_proto_features_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_examples_geo_proto_features_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Features); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_examples_geo_proto_features_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Features_Coordinate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_examples_geo_proto_features_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Features_PoiFeature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_examples_geo_proto_features_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Features_TrackFeature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_examples_geo_proto_features_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Features_PoiFeature_Marker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_examples_geo_proto_features_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Features_TrackFeature_Stroke); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_examples_geo_proto_features_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_geo_proto_features_proto_goTypes,
		DependencyIndexes: file_examples_geo_proto_features_proto_depIdxs,
		EnumInfos:         file_examples_geo_proto_features_proto_enumTypes,
		MessageInfos:      file_examples_geo_proto_features_proto_msgTypes,
	}.Build()
	File_examples_geo_proto_features_proto = out.File
	file_examples_geo_proto_features_proto_rawDesc = nil
	file_examples_geo_proto_features_proto_goTypes = nil
	file_examples_geo_proto_features_proto_depIdxs = nil
}
