// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.11.3
// source: valid/field.proto

package valid

import (
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Level int32

const (
	Level_LEVEL_UNSPECIFIED Level = 0
	Level_LEVEL_DEBUG       Level = 1
	Level_LEVEL_INFO        Level = 2
	Level_LEVEL_WARN        Level = 3
	Level_LEVEL_ERROR       Level = 4
)

// Enum value maps for Level.
var (
	Level_name = map[int32]string{
		0: "LEVEL_UNSPECIFIED",
		1: "LEVEL_DEBUG",
		2: "LEVEL_INFO",
		3: "LEVEL_WARN",
		4: "LEVEL_ERROR",
	}
	Level_value = map[string]int32{
		"LEVEL_UNSPECIFIED": 0,
		"LEVEL_DEBUG":       1,
		"LEVEL_INFO":        2,
		"LEVEL_WARN":        3,
		"LEVEL_ERROR":       4,
	}
)

func (x Level) Enum() *Level {
	p := new(Level)
	*p = x
	return p
}

func (x Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Level) Descriptor() protoreflect.EnumDescriptor {
	return file_valid_field_proto_enumTypes[0].Descriptor()
}

func (Level) Type() protoreflect.EnumType {
	return &file_valid_field_proto_enumTypes[0]
}

func (x Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Level.Descriptor instead.
func (Level) EnumDescriptor() ([]byte, []int) {
	return file_valid_field_proto_rawDescGZIP(), []int{0}
}

type FieldConstraints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//	*FieldConstraints_Double
	//	*FieldConstraints_Float
	//	*FieldConstraints_Int32
	//	*FieldConstraints_Int64
	//	*FieldConstraints_Bool
	//	*FieldConstraints_String_
	//	*FieldConstraints_Bytes
	//	*FieldConstraints_Repeated
	//	*FieldConstraints_Map
	//	*FieldConstraints_Enum
	Type isFieldConstraints_Type `protobuf_oneof:"type"`
}

func (x *FieldConstraints) Reset() {
	*x = FieldConstraints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valid_field_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldConstraints) ProtoMessage() {}

func (x *FieldConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_valid_field_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldConstraints.ProtoReflect.Descriptor instead.
func (*FieldConstraints) Descriptor() ([]byte, []int) {
	return file_valid_field_proto_rawDescGZIP(), []int{0}
}

func (m *FieldConstraints) GetType() isFieldConstraints_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *FieldConstraints) GetDouble() *FieldConstraints_DoubleConstraints {
	if x, ok := x.GetType().(*FieldConstraints_Double); ok {
		return x.Double
	}
	return nil
}

func (x *FieldConstraints) GetFloat() *FieldConstraints_FloatConstraints {
	if x, ok := x.GetType().(*FieldConstraints_Float); ok {
		return x.Float
	}
	return nil
}

func (x *FieldConstraints) GetInt32() *FieldConstraints_Int32Constraints {
	if x, ok := x.GetType().(*FieldConstraints_Int32); ok {
		return x.Int32
	}
	return nil
}

func (x *FieldConstraints) GetInt64() *FieldConstraints_Int64Constraints {
	if x, ok := x.GetType().(*FieldConstraints_Int64); ok {
		return x.Int64
	}
	return nil
}

func (x *FieldConstraints) GetBool() *FieldConstraints_BoolConstraints {
	if x, ok := x.GetType().(*FieldConstraints_Bool); ok {
		return x.Bool
	}
	return nil
}

func (x *FieldConstraints) GetString_() *FieldConstraints_StringConstraints {
	if x, ok := x.GetType().(*FieldConstraints_String_); ok {
		return x.String_
	}
	return nil
}

func (x *FieldConstraints) GetBytes() *FieldConstraints_BytesConstraints {
	if x, ok := x.GetType().(*FieldConstraints_Bytes); ok {
		return x.Bytes
	}
	return nil
}

func (x *FieldConstraints) GetRepeated() *FieldConstraints_RepeatedConstraints {
	if x, ok := x.GetType().(*FieldConstraints_Repeated); ok {
		return x.Repeated
	}
	return nil
}

func (x *FieldConstraints) GetMap() *FieldConstraints_MapConstraints {
	if x, ok := x.GetType().(*FieldConstraints_Map); ok {
		return x.Map
	}
	return nil
}

func (x *FieldConstraints) GetEnum() *FieldConstraints_EnumConstraints {
	if x, ok := x.GetType().(*FieldConstraints_Enum); ok {
		return x.Enum
	}
	return nil
}

type isFieldConstraints_Type interface {
	isFieldConstraints_Type()
}

type FieldConstraints_Double struct {
	Double *FieldConstraints_DoubleConstraints `protobuf:"bytes,1,opt,name=double,proto3,oneof"`
}

type FieldConstraints_Float struct {
	Float *FieldConstraints_FloatConstraints `protobuf:"bytes,2,opt,name=float,proto3,oneof"`
}

type FieldConstraints_Int32 struct {
	Int32 *FieldConstraints_Int32Constraints `protobuf:"bytes,3,opt,name=int32,proto3,oneof"`
}

type FieldConstraints_Int64 struct {
	Int64 *FieldConstraints_Int64Constraints `protobuf:"bytes,4,opt,name=int64,proto3,oneof"`
}

type FieldConstraints_Bool struct {
	// uint32
	// uint64
	// sint32
	// sint64
	// fixed32
	// fixed64
	// sfixed32
	// sfixed64
	Bool *FieldConstraints_BoolConstraints `protobuf:"bytes,13,opt,name=bool,proto3,oneof"`
}

type FieldConstraints_String_ struct {
	String_ *FieldConstraints_StringConstraints `protobuf:"bytes,14,opt,name=string,proto3,oneof"`
}

type FieldConstraints_Bytes struct {
	Bytes *FieldConstraints_BytesConstraints `protobuf:"bytes,15,opt,name=bytes,proto3,oneof"`
}

type FieldConstraints_Repeated struct {
	Repeated *FieldConstraints_RepeatedConstraints `protobuf:"bytes,16,opt,name=repeated,proto3,oneof"`
}

type FieldConstraints_Map struct {
	Map *FieldConstraints_MapConstraints `protobuf:"bytes,17,opt,name=map,proto3,oneof"`
}

type FieldConstraints_Enum struct {
	Enum *FieldConstraints_EnumConstraints `protobuf:"bytes,18,opt,name=enum,proto3,oneof"`
}

func (*FieldConstraints_Double) isFieldConstraints_Type() {}

func (*FieldConstraints_Float) isFieldConstraints_Type() {}

func (*FieldConstraints_Int32) isFieldConstraints_Type() {}

func (*FieldConstraints_Int64) isFieldConstraints_Type() {}

func (*FieldConstraints_Bool) isFieldConstraints_Type() {}

func (*FieldConstraints_String_) isFieldConstraints_Type() {}

func (*FieldConstraints_Bytes) isFieldConstraints_Type() {}

func (*FieldConstraints_Repeated) isFieldConstraints_Type() {}

func (*FieldConstraints_Map) isFieldConstraints_Type() {}

func (*FieldConstraints_Enum) isFieldConstraints_Type() {}

type FieldConstraints_DoubleConstraints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Min:
	//	*FieldConstraints_DoubleConstraints_Gte
	//	*FieldConstraints_DoubleConstraints_Gt
	Min isFieldConstraints_DoubleConstraints_Min `protobuf_oneof:"min"`
	// Types that are assignable to Max:
	//	*FieldConstraints_DoubleConstraints_Lte
	//	*FieldConstraints_DoubleConstraints_Lt
	Max   isFieldConstraints_DoubleConstraints_Max `protobuf_oneof:"max"`
	Eps   float64                                  `protobuf:"fixed64,5,opt,name=eps,proto3" json:"eps,omitempty"`
	Msg   string                                   `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty"`
	Level Level                                    `protobuf:"varint,7,opt,name=level,proto3,enum=valid.Level" json:"level,omitempty"`
}

func (x *FieldConstraints_DoubleConstraints) Reset() {
	*x = FieldConstraints_DoubleConstraints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valid_field_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldConstraints_DoubleConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldConstraints_DoubleConstraints) ProtoMessage() {}

func (x *FieldConstraints_DoubleConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_valid_field_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldConstraints_DoubleConstraints.ProtoReflect.Descriptor instead.
func (*FieldConstraints_DoubleConstraints) Descriptor() ([]byte, []int) {
	return file_valid_field_proto_rawDescGZIP(), []int{0, 0}
}

func (m *FieldConstraints_DoubleConstraints) GetMin() isFieldConstraints_DoubleConstraints_Min {
	if m != nil {
		return m.Min
	}
	return nil
}

func (x *FieldConstraints_DoubleConstraints) GetGte() float64 {
	if x, ok := x.GetMin().(*FieldConstraints_DoubleConstraints_Gte); ok {
		return x.Gte
	}
	return 0
}

func (x *FieldConstraints_DoubleConstraints) GetGt() float64 {
	if x, ok := x.GetMin().(*FieldConstraints_DoubleConstraints_Gt); ok {
		return x.Gt
	}
	return 0
}

func (m *FieldConstraints_DoubleConstraints) GetMax() isFieldConstraints_DoubleConstraints_Max {
	if m != nil {
		return m.Max
	}
	return nil
}

func (x *FieldConstraints_DoubleConstraints) GetLte() float64 {
	if x, ok := x.GetMax().(*FieldConstraints_DoubleConstraints_Lte); ok {
		return x.Lte
	}
	return 0
}

func (x *FieldConstraints_DoubleConstraints) GetLt() float64 {
	if x, ok := x.GetMax().(*FieldConstraints_DoubleConstraints_Lt); ok {
		return x.Lt
	}
	return 0
}

func (x *FieldConstraints_DoubleConstraints) GetEps() float64 {
	if x != nil {
		return x.Eps
	}
	return 0
}

func (x *FieldConstraints_DoubleConstraints) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FieldConstraints_DoubleConstraints) GetLevel() Level {
	if x != nil {
		return x.Level
	}
	return Level_LEVEL_UNSPECIFIED
}

type isFieldConstraints_DoubleConstraints_Min interface {
	isFieldConstraints_DoubleConstraints_Min()
}

type FieldConstraints_DoubleConstraints_Gte struct {
	Gte float64 `protobuf:"fixed64,1,opt,name=gte,proto3,oneof"`
}

type FieldConstraints_DoubleConstraints_Gt struct {
	Gt float64 `protobuf:"fixed64,2,opt,name=gt,proto3,oneof"`
}

func (*FieldConstraints_DoubleConstraints_Gte) isFieldConstraints_DoubleConstraints_Min() {}

func (*FieldConstraints_DoubleConstraints_Gt) isFieldConstraints_DoubleConstraints_Min() {}

type isFieldConstraints_DoubleConstraints_Max interface {
	isFieldConstraints_DoubleConstraints_Max()
}

type FieldConstraints_DoubleConstraints_Lte struct {
	Lte float64 `protobuf:"fixed64,3,opt,name=lte,proto3,oneof"`
}

type FieldConstraints_DoubleConstraints_Lt struct {
	Lt float64 `protobuf:"fixed64,4,opt,name=lt,proto3,oneof"`
}

func (*FieldConstraints_DoubleConstraints_Lte) isFieldConstraints_DoubleConstraints_Max() {}

func (*FieldConstraints_DoubleConstraints_Lt) isFieldConstraints_DoubleConstraints_Max() {}

type FieldConstraints_FloatConstraints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Min:
	//	*FieldConstraints_FloatConstraints_Gte
	//	*FieldConstraints_FloatConstraints_Gt
	Min isFieldConstraints_FloatConstraints_Min `protobuf_oneof:"min"`
	// Types that are assignable to Max:
	//	*FieldConstraints_FloatConstraints_Lte
	//	*FieldConstraints_FloatConstraints_Lt
	Max   isFieldConstraints_FloatConstraints_Max `protobuf_oneof:"max"`
	Eps   float64                                 `protobuf:"fixed64,5,opt,name=eps,proto3" json:"eps,omitempty"`
	Msg   string                                  `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty"`
	Level Level                                   `protobuf:"varint,7,opt,name=level,proto3,enum=valid.Level" json:"level,omitempty"`
}

func (x *FieldConstraints_FloatConstraints) Reset() {
	*x = FieldConstraints_FloatConstraints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valid_field_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldConstraints_FloatConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldConstraints_FloatConstraints) ProtoMessage() {}

func (x *FieldConstraints_FloatConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_valid_field_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldConstraints_FloatConstraints.ProtoReflect.Descriptor instead.
func (*FieldConstraints_FloatConstraints) Descriptor() ([]byte, []int) {
	return file_valid_field_proto_rawDescGZIP(), []int{0, 1}
}

func (m *FieldConstraints_FloatConstraints) GetMin() isFieldConstraints_FloatConstraints_Min {
	if m != nil {
		return m.Min
	}
	return nil
}

func (x *FieldConstraints_FloatConstraints) GetGte() float64 {
	if x, ok := x.GetMin().(*FieldConstraints_FloatConstraints_Gte); ok {
		return x.Gte
	}
	return 0
}

func (x *FieldConstraints_FloatConstraints) GetGt() float64 {
	if x, ok := x.GetMin().(*FieldConstraints_FloatConstraints_Gt); ok {
		return x.Gt
	}
	return 0
}

func (m *FieldConstraints_FloatConstraints) GetMax() isFieldConstraints_FloatConstraints_Max {
	if m != nil {
		return m.Max
	}
	return nil
}

func (x *FieldConstraints_FloatConstraints) GetLte() float64 {
	if x, ok := x.GetMax().(*FieldConstraints_FloatConstraints_Lte); ok {
		return x.Lte
	}
	return 0
}

func (x *FieldConstraints_FloatConstraints) GetLt() float64 {
	if x, ok := x.GetMax().(*FieldConstraints_FloatConstraints_Lt); ok {
		return x.Lt
	}
	return 0
}

func (x *FieldConstraints_FloatConstraints) GetEps() float64 {
	if x != nil {
		return x.Eps
	}
	return 0
}

func (x *FieldConstraints_FloatConstraints) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FieldConstraints_FloatConstraints) GetLevel() Level {
	if x != nil {
		return x.Level
	}
	return Level_LEVEL_UNSPECIFIED
}

type isFieldConstraints_FloatConstraints_Min interface {
	isFieldConstraints_FloatConstraints_Min()
}

type FieldConstraints_FloatConstraints_Gte struct {
	Gte float64 `protobuf:"fixed64,1,opt,name=gte,proto3,oneof"`
}

type FieldConstraints_FloatConstraints_Gt struct {
	Gt float64 `protobuf:"fixed64,2,opt,name=gt,proto3,oneof"`
}

func (*FieldConstraints_FloatConstraints_Gte) isFieldConstraints_FloatConstraints_Min() {}

func (*FieldConstraints_FloatConstraints_Gt) isFieldConstraints_FloatConstraints_Min() {}

type isFieldConstraints_FloatConstraints_Max interface {
	isFieldConstraints_FloatConstraints_Max()
}

type FieldConstraints_FloatConstraints_Lte struct {
	Lte float64 `protobuf:"fixed64,3,opt,name=lte,proto3,oneof"`
}

type FieldConstraints_FloatConstraints_Lt struct {
	Lt float64 `protobuf:"fixed64,4,opt,name=lt,proto3,oneof"`
}

func (*FieldConstraints_FloatConstraints_Lte) isFieldConstraints_FloatConstraints_Max() {}

func (*FieldConstraints_FloatConstraints_Lt) isFieldConstraints_FloatConstraints_Max() {}

type FieldConstraints_Int32Constraints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Min:
	//	*FieldConstraints_Int32Constraints_Gte
	//	*FieldConstraints_Int32Constraints_Gt
	Min isFieldConstraints_Int32Constraints_Min `protobuf_oneof:"min"`
	// Types that are assignable to Max:
	//	*FieldConstraints_Int32Constraints_Lte
	//	*FieldConstraints_Int32Constraints_Lt
	Max   isFieldConstraints_Int32Constraints_Max `protobuf_oneof:"max"`
	In    []int32                                 `protobuf:"varint,5,rep,packed,name=in,proto3" json:"in,omitempty"`
	NotIn []int32                                 `protobuf:"varint,6,rep,packed,name=not_in,json=notIn,proto3" json:"not_in,omitempty"`
	Eq    int32                                   `protobuf:"varint,7,opt,name=eq,proto3" json:"eq,omitempty"`
	Msg   string                                  `protobuf:"bytes,8,opt,name=msg,proto3" json:"msg,omitempty"`
	Level Level                                   `protobuf:"varint,9,opt,name=level,proto3,enum=valid.Level" json:"level,omitempty"`
}

func (x *FieldConstraints_Int32Constraints) Reset() {
	*x = FieldConstraints_Int32Constraints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valid_field_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldConstraints_Int32Constraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldConstraints_Int32Constraints) ProtoMessage() {}

func (x *FieldConstraints_Int32Constraints) ProtoReflect() protoreflect.Message {
	mi := &file_valid_field_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldConstraints_Int32Constraints.ProtoReflect.Descriptor instead.
func (*FieldConstraints_Int32Constraints) Descriptor() ([]byte, []int) {
	return file_valid_field_proto_rawDescGZIP(), []int{0, 2}
}

func (m *FieldConstraints_Int32Constraints) GetMin() isFieldConstraints_Int32Constraints_Min {
	if m != nil {
		return m.Min
	}
	return nil
}

func (x *FieldConstraints_Int32Constraints) GetGte() int32 {
	if x, ok := x.GetMin().(*FieldConstraints_Int32Constraints_Gte); ok {
		return x.Gte
	}
	return 0
}

func (x *FieldConstraints_Int32Constraints) GetGt() int32 {
	if x, ok := x.GetMin().(*FieldConstraints_Int32Constraints_Gt); ok {
		return x.Gt
	}
	return 0
}

func (m *FieldConstraints_Int32Constraints) GetMax() isFieldConstraints_Int32Constraints_Max {
	if m != nil {
		return m.Max
	}
	return nil
}

func (x *FieldConstraints_Int32Constraints) GetLte() int32 {
	if x, ok := x.GetMax().(*FieldConstraints_Int32Constraints_Lte); ok {
		return x.Lte
	}
	return 0
}

func (x *FieldConstraints_Int32Constraints) GetLt() int32 {
	if x, ok := x.GetMax().(*FieldConstraints_Int32Constraints_Lt); ok {
		return x.Lt
	}
	return 0
}

func (x *FieldConstraints_Int32Constraints) GetIn() []int32 {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *FieldConstraints_Int32Constraints) GetNotIn() []int32 {
	if x != nil {
		return x.NotIn
	}
	return nil
}

func (x *FieldConstraints_Int32Constraints) GetEq() int32 {
	if x != nil {
		return x.Eq
	}
	return 0
}

func (x *FieldConstraints_Int32Constraints) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FieldConstraints_Int32Constraints) GetLevel() Level {
	if x != nil {
		return x.Level
	}
	return Level_LEVEL_UNSPECIFIED
}

type isFieldConstraints_Int32Constraints_Min interface {
	isFieldConstraints_Int32Constraints_Min()
}

type FieldConstraints_Int32Constraints_Gte struct {
	Gte int32 `protobuf:"varint,1,opt,name=gte,proto3,oneof"`
}

type FieldConstraints_Int32Constraints_Gt struct {
	Gt int32 `protobuf:"varint,2,opt,name=gt,proto3,oneof"`
}

func (*FieldConstraints_Int32Constraints_Gte) isFieldConstraints_Int32Constraints_Min() {}

func (*FieldConstraints_Int32Constraints_Gt) isFieldConstraints_Int32Constraints_Min() {}

type isFieldConstraints_Int32Constraints_Max interface {
	isFieldConstraints_Int32Constraints_Max()
}

type FieldConstraints_Int32Constraints_Lte struct {
	Lte int32 `protobuf:"varint,3,opt,name=lte,proto3,oneof"`
}

type FieldConstraints_Int32Constraints_Lt struct {
	Lt int32 `protobuf:"varint,4,opt,name=lt,proto3,oneof"`
}

func (*FieldConstraints_Int32Constraints_Lte) isFieldConstraints_Int32Constraints_Max() {}

func (*FieldConstraints_Int32Constraints_Lt) isFieldConstraints_Int32Constraints_Max() {}

type FieldConstraints_Int64Constraints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Min:
	//	*FieldConstraints_Int64Constraints_Gte
	//	*FieldConstraints_Int64Constraints_Gt
	Min isFieldConstraints_Int64Constraints_Min `protobuf_oneof:"min"`
	// Types that are assignable to Max:
	//	*FieldConstraints_Int64Constraints_Lte
	//	*FieldConstraints_Int64Constraints_Lt
	Max   isFieldConstraints_Int64Constraints_Max `protobuf_oneof:"max"`
	In    []int64                                 `protobuf:"varint,5,rep,packed,name=in,proto3" json:"in,omitempty"`
	NotIn []int64                                 `protobuf:"varint,6,rep,packed,name=not_in,json=notIn,proto3" json:"not_in,omitempty"`
	Eq    int64                                   `protobuf:"varint,7,opt,name=eq,proto3" json:"eq,omitempty"`
	Msg   string                                  `protobuf:"bytes,8,opt,name=msg,proto3" json:"msg,omitempty"`
	Level Level                                   `protobuf:"varint,9,opt,name=level,proto3,enum=valid.Level" json:"level,omitempty"`
}

func (x *FieldConstraints_Int64Constraints) Reset() {
	*x = FieldConstraints_Int64Constraints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valid_field_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldConstraints_Int64Constraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldConstraints_Int64Constraints) ProtoMessage() {}

func (x *FieldConstraints_Int64Constraints) ProtoReflect() protoreflect.Message {
	mi := &file_valid_field_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldConstraints_Int64Constraints.ProtoReflect.Descriptor instead.
func (*FieldConstraints_Int64Constraints) Descriptor() ([]byte, []int) {
	return file_valid_field_proto_rawDescGZIP(), []int{0, 3}
}

func (m *FieldConstraints_Int64Constraints) GetMin() isFieldConstraints_Int64Constraints_Min {
	if m != nil {
		return m.Min
	}
	return nil
}

func (x *FieldConstraints_Int64Constraints) GetGte() int64 {
	if x, ok := x.GetMin().(*FieldConstraints_Int64Constraints_Gte); ok {
		return x.Gte
	}
	return 0
}

func (x *FieldConstraints_Int64Constraints) GetGt() int64 {
	if x, ok := x.GetMin().(*FieldConstraints_Int64Constraints_Gt); ok {
		return x.Gt
	}
	return 0
}

func (m *FieldConstraints_Int64Constraints) GetMax() isFieldConstraints_Int64Constraints_Max {
	if m != nil {
		return m.Max
	}
	return nil
}

func (x *FieldConstraints_Int64Constraints) GetLte() int64 {
	if x, ok := x.GetMax().(*FieldConstraints_Int64Constraints_Lte); ok {
		return x.Lte
	}
	return 0
}

func (x *FieldConstraints_Int64Constraints) GetLt() int64 {
	if x, ok := x.GetMax().(*FieldConstraints_Int64Constraints_Lt); ok {
		return x.Lt
	}
	return 0
}

func (x *FieldConstraints_Int64Constraints) GetIn() []int64 {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *FieldConstraints_Int64Constraints) GetNotIn() []int64 {
	if x != nil {
		return x.NotIn
	}
	return nil
}

func (x *FieldConstraints_Int64Constraints) GetEq() int64 {
	if x != nil {
		return x.Eq
	}
	return 0
}

func (x *FieldConstraints_Int64Constraints) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FieldConstraints_Int64Constraints) GetLevel() Level {
	if x != nil {
		return x.Level
	}
	return Level_LEVEL_UNSPECIFIED
}

type isFieldConstraints_Int64Constraints_Min interface {
	isFieldConstraints_Int64Constraints_Min()
}

type FieldConstraints_Int64Constraints_Gte struct {
	Gte int64 `protobuf:"varint,1,opt,name=gte,proto3,oneof"`
}

type FieldConstraints_Int64Constraints_Gt struct {
	Gt int64 `protobuf:"varint,2,opt,name=gt,proto3,oneof"`
}

func (*FieldConstraints_Int64Constraints_Gte) isFieldConstraints_Int64Constraints_Min() {}

func (*FieldConstraints_Int64Constraints_Gt) isFieldConstraints_Int64Constraints_Min() {}

type isFieldConstraints_Int64Constraints_Max interface {
	isFieldConstraints_Int64Constraints_Max()
}

type FieldConstraints_Int64Constraints_Lte struct {
	Lte int64 `protobuf:"varint,3,opt,name=lte,proto3,oneof"`
}

type FieldConstraints_Int64Constraints_Lt struct {
	Lt int64 `protobuf:"varint,4,opt,name=lt,proto3,oneof"`
}

func (*FieldConstraints_Int64Constraints_Lte) isFieldConstraints_Int64Constraints_Max() {}

func (*FieldConstraints_Int64Constraints_Lt) isFieldConstraints_Int64Constraints_Max() {}

type FieldConstraints_BoolConstraints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Eq bool `protobuf:"varint,1,opt,name=eq,proto3" json:"eq,omitempty"`
}

func (x *FieldConstraints_BoolConstraints) Reset() {
	*x = FieldConstraints_BoolConstraints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valid_field_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldConstraints_BoolConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldConstraints_BoolConstraints) ProtoMessage() {}

func (x *FieldConstraints_BoolConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_valid_field_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldConstraints_BoolConstraints.ProtoReflect.Descriptor instead.
func (*FieldConstraints_BoolConstraints) Descriptor() ([]byte, []int) {
	return file_valid_field_proto_rawDescGZIP(), []int{0, 4}
}

func (x *FieldConstraints_BoolConstraints) GetEq() bool {
	if x != nil {
		return x.Eq
	}
	return false
}

type FieldConstraints_StringConstraints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to EmptyType:
	//	*FieldConstraints_StringConstraints_Empty
	//	*FieldConstraints_StringConstraints_NotEmpty
	EmptyType isFieldConstraints_StringConstraints_EmptyType `protobuf_oneof:"empty_type"`
	LenEq     uint32                                         `protobuf:"varint,3,opt,name=len_eq,json=lenEq,proto3" json:"len_eq,omitempty"`
	LenGte    uint32                                         `protobuf:"varint,4,opt,name=len_gte,json=lenGte,proto3" json:"len_gte,omitempty"`
	LenLte    uint32                                         `protobuf:"varint,5,opt,name=len_lte,json=lenLte,proto3" json:"len_lte,omitempty"`
	Eq        string                                         `protobuf:"bytes,6,opt,name=eq,proto3" json:"eq,omitempty"`
	Pattern   string                                         `protobuf:"bytes,7,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Msg       string                                         `protobuf:"bytes,8,opt,name=msg,proto3" json:"msg,omitempty"`
	Level     Level                                          `protobuf:"varint,9,opt,name=level,proto3,enum=valid.Level" json:"level,omitempty"`
}

func (x *FieldConstraints_StringConstraints) Reset() {
	*x = FieldConstraints_StringConstraints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valid_field_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldConstraints_StringConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldConstraints_StringConstraints) ProtoMessage() {}

func (x *FieldConstraints_StringConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_valid_field_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldConstraints_StringConstraints.ProtoReflect.Descriptor instead.
func (*FieldConstraints_StringConstraints) Descriptor() ([]byte, []int) {
	return file_valid_field_proto_rawDescGZIP(), []int{0, 5}
}

func (m *FieldConstraints_StringConstraints) GetEmptyType() isFieldConstraints_StringConstraints_EmptyType {
	if m != nil {
		return m.EmptyType
	}
	return nil
}

func (x *FieldConstraints_StringConstraints) GetEmpty() bool {
	if x, ok := x.GetEmptyType().(*FieldConstraints_StringConstraints_Empty); ok {
		return x.Empty
	}
	return false
}

func (x *FieldConstraints_StringConstraints) GetNotEmpty() bool {
	if x, ok := x.GetEmptyType().(*FieldConstraints_StringConstraints_NotEmpty); ok {
		return x.NotEmpty
	}
	return false
}

func (x *FieldConstraints_StringConstraints) GetLenEq() uint32 {
	if x != nil {
		return x.LenEq
	}
	return 0
}

func (x *FieldConstraints_StringConstraints) GetLenGte() uint32 {
	if x != nil {
		return x.LenGte
	}
	return 0
}

func (x *FieldConstraints_StringConstraints) GetLenLte() uint32 {
	if x != nil {
		return x.LenLte
	}
	return 0
}

func (x *FieldConstraints_StringConstraints) GetEq() string {
	if x != nil {
		return x.Eq
	}
	return ""
}

func (x *FieldConstraints_StringConstraints) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *FieldConstraints_StringConstraints) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FieldConstraints_StringConstraints) GetLevel() Level {
	if x != nil {
		return x.Level
	}
	return Level_LEVEL_UNSPECIFIED
}

type isFieldConstraints_StringConstraints_EmptyType interface {
	isFieldConstraints_StringConstraints_EmptyType()
}

type FieldConstraints_StringConstraints_Empty struct {
	Empty bool `protobuf:"varint,1,opt,name=empty,proto3,oneof"`
}

type FieldConstraints_StringConstraints_NotEmpty struct {
	NotEmpty bool `protobuf:"varint,2,opt,name=not_empty,json=notEmpty,proto3,oneof"`
}

func (*FieldConstraints_StringConstraints_Empty) isFieldConstraints_StringConstraints_EmptyType() {}

func (*FieldConstraints_StringConstraints_NotEmpty) isFieldConstraints_StringConstraints_EmptyType() {
}

type FieldConstraints_BytesConstraints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to EmptyType:
	//	*FieldConstraints_BytesConstraints_Empty
	//	*FieldConstraints_BytesConstraints_NotEmpty
	EmptyType isFieldConstraints_BytesConstraints_EmptyType `protobuf_oneof:"empty_type"`
	LenEq     uint32                                        `protobuf:"varint,3,opt,name=len_eq,json=lenEq,proto3" json:"len_eq,omitempty"`
	LenGte    uint32                                        `protobuf:"varint,4,opt,name=len_gte,json=lenGte,proto3" json:"len_gte,omitempty"`
	LenLte    uint32                                        `protobuf:"varint,5,opt,name=len_lte,json=lenLte,proto3" json:"len_lte,omitempty"`
	Msg       string                                        `protobuf:"bytes,8,opt,name=msg,proto3" json:"msg,omitempty"`
	Level     Level                                         `protobuf:"varint,9,opt,name=level,proto3,enum=valid.Level" json:"level,omitempty"`
}

func (x *FieldConstraints_BytesConstraints) Reset() {
	*x = FieldConstraints_BytesConstraints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valid_field_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldConstraints_BytesConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldConstraints_BytesConstraints) ProtoMessage() {}

func (x *FieldConstraints_BytesConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_valid_field_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldConstraints_BytesConstraints.ProtoReflect.Descriptor instead.
func (*FieldConstraints_BytesConstraints) Descriptor() ([]byte, []int) {
	return file_valid_field_proto_rawDescGZIP(), []int{0, 6}
}

func (m *FieldConstraints_BytesConstraints) GetEmptyType() isFieldConstraints_BytesConstraints_EmptyType {
	if m != nil {
		return m.EmptyType
	}
	return nil
}

func (x *FieldConstraints_BytesConstraints) GetEmpty() bool {
	if x, ok := x.GetEmptyType().(*FieldConstraints_BytesConstraints_Empty); ok {
		return x.Empty
	}
	return false
}

func (x *FieldConstraints_BytesConstraints) GetNotEmpty() bool {
	if x, ok := x.GetEmptyType().(*FieldConstraints_BytesConstraints_NotEmpty); ok {
		return x.NotEmpty
	}
	return false
}

func (x *FieldConstraints_BytesConstraints) GetLenEq() uint32 {
	if x != nil {
		return x.LenEq
	}
	return 0
}

func (x *FieldConstraints_BytesConstraints) GetLenGte() uint32 {
	if x != nil {
		return x.LenGte
	}
	return 0
}

func (x *FieldConstraints_BytesConstraints) GetLenLte() uint32 {
	if x != nil {
		return x.LenLte
	}
	return 0
}

func (x *FieldConstraints_BytesConstraints) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FieldConstraints_BytesConstraints) GetLevel() Level {
	if x != nil {
		return x.Level
	}
	return Level_LEVEL_UNSPECIFIED
}

type isFieldConstraints_BytesConstraints_EmptyType interface {
	isFieldConstraints_BytesConstraints_EmptyType()
}

type FieldConstraints_BytesConstraints_Empty struct {
	Empty bool `protobuf:"varint,1,opt,name=empty,proto3,oneof"`
}

type FieldConstraints_BytesConstraints_NotEmpty struct {
	NotEmpty bool `protobuf:"varint,2,opt,name=not_empty,json=notEmpty,proto3,oneof"`
}

func (*FieldConstraints_BytesConstraints_Empty) isFieldConstraints_BytesConstraints_EmptyType() {}

func (*FieldConstraints_BytesConstraints_NotEmpty) isFieldConstraints_BytesConstraints_EmptyType() {}

type FieldConstraints_RepeatedConstraints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to EmptyType:
	//	*FieldConstraints_RepeatedConstraints_Empty
	//	*FieldConstraints_RepeatedConstraints_NotEmpty
	EmptyType isFieldConstraints_RepeatedConstraints_EmptyType `protobuf_oneof:"empty_type"`
	LenGte    uint32                                           `protobuf:"varint,3,opt,name=len_gte,json=lenGte,proto3" json:"len_gte,omitempty"`
	LenLte    uint32                                           `protobuf:"varint,4,opt,name=len_lte,json=lenLte,proto3" json:"len_lte,omitempty"`
	LenEq     uint32                                           `protobuf:"varint,5,opt,name=len_eq,json=lenEq,proto3" json:"len_eq,omitempty"`
	Msg       string                                           `protobuf:"bytes,8,opt,name=msg,proto3" json:"msg,omitempty"`
	Level     Level                                            `protobuf:"varint,9,opt,name=level,proto3,enum=valid.Level" json:"level,omitempty"`
	Elems     *FieldConstraints                                `protobuf:"bytes,10,opt,name=elems,proto3" json:"elems,omitempty"`
}

func (x *FieldConstraints_RepeatedConstraints) Reset() {
	*x = FieldConstraints_RepeatedConstraints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valid_field_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldConstraints_RepeatedConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldConstraints_RepeatedConstraints) ProtoMessage() {}

func (x *FieldConstraints_RepeatedConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_valid_field_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldConstraints_RepeatedConstraints.ProtoReflect.Descriptor instead.
func (*FieldConstraints_RepeatedConstraints) Descriptor() ([]byte, []int) {
	return file_valid_field_proto_rawDescGZIP(), []int{0, 7}
}

func (m *FieldConstraints_RepeatedConstraints) GetEmptyType() isFieldConstraints_RepeatedConstraints_EmptyType {
	if m != nil {
		return m.EmptyType
	}
	return nil
}

func (x *FieldConstraints_RepeatedConstraints) GetEmpty() bool {
	if x, ok := x.GetEmptyType().(*FieldConstraints_RepeatedConstraints_Empty); ok {
		return x.Empty
	}
	return false
}

func (x *FieldConstraints_RepeatedConstraints) GetNotEmpty() bool {
	if x, ok := x.GetEmptyType().(*FieldConstraints_RepeatedConstraints_NotEmpty); ok {
		return x.NotEmpty
	}
	return false
}

func (x *FieldConstraints_RepeatedConstraints) GetLenGte() uint32 {
	if x != nil {
		return x.LenGte
	}
	return 0
}

func (x *FieldConstraints_RepeatedConstraints) GetLenLte() uint32 {
	if x != nil {
		return x.LenLte
	}
	return 0
}

func (x *FieldConstraints_RepeatedConstraints) GetLenEq() uint32 {
	if x != nil {
		return x.LenEq
	}
	return 0
}

func (x *FieldConstraints_RepeatedConstraints) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FieldConstraints_RepeatedConstraints) GetLevel() Level {
	if x != nil {
		return x.Level
	}
	return Level_LEVEL_UNSPECIFIED
}

func (x *FieldConstraints_RepeatedConstraints) GetElems() *FieldConstraints {
	if x != nil {
		return x.Elems
	}
	return nil
}

type isFieldConstraints_RepeatedConstraints_EmptyType interface {
	isFieldConstraints_RepeatedConstraints_EmptyType()
}

type FieldConstraints_RepeatedConstraints_Empty struct {
	Empty bool `protobuf:"varint,1,opt,name=empty,proto3,oneof"`
}

type FieldConstraints_RepeatedConstraints_NotEmpty struct {
	NotEmpty bool `protobuf:"varint,2,opt,name=not_empty,json=notEmpty,proto3,oneof"`
}

func (*FieldConstraints_RepeatedConstraints_Empty) isFieldConstraints_RepeatedConstraints_EmptyType() {
}

func (*FieldConstraints_RepeatedConstraints_NotEmpty) isFieldConstraints_RepeatedConstraints_EmptyType() {
}

type FieldConstraints_MapConstraints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to EmptyType:
	//	*FieldConstraints_MapConstraints_Empty
	//	*FieldConstraints_MapConstraints_NotEmpty
	EmptyType isFieldConstraints_MapConstraints_EmptyType `protobuf_oneof:"empty_type"`
	LenGte    uint32                                      `protobuf:"varint,3,opt,name=len_gte,json=lenGte,proto3" json:"len_gte,omitempty"`
	LenLte    uint32                                      `protobuf:"varint,4,opt,name=len_lte,json=lenLte,proto3" json:"len_lte,omitempty"`
	LenEq     uint32                                      `protobuf:"varint,5,opt,name=len_eq,json=lenEq,proto3" json:"len_eq,omitempty"`
	Msg       string                                      `protobuf:"bytes,8,opt,name=msg,proto3" json:"msg,omitempty"`
	Level     Level                                       `protobuf:"varint,9,opt,name=level,proto3,enum=valid.Level" json:"level,omitempty"`
	Keys      *FieldConstraints                           `protobuf:"bytes,10,opt,name=keys,proto3" json:"keys,omitempty"`
	Values    *FieldConstraints                           `protobuf:"bytes,11,opt,name=values,proto3" json:"values,omitempty"`
}

func (x *FieldConstraints_MapConstraints) Reset() {
	*x = FieldConstraints_MapConstraints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valid_field_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldConstraints_MapConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldConstraints_MapConstraints) ProtoMessage() {}

func (x *FieldConstraints_MapConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_valid_field_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldConstraints_MapConstraints.ProtoReflect.Descriptor instead.
func (*FieldConstraints_MapConstraints) Descriptor() ([]byte, []int) {
	return file_valid_field_proto_rawDescGZIP(), []int{0, 8}
}

func (m *FieldConstraints_MapConstraints) GetEmptyType() isFieldConstraints_MapConstraints_EmptyType {
	if m != nil {
		return m.EmptyType
	}
	return nil
}

func (x *FieldConstraints_MapConstraints) GetEmpty() bool {
	if x, ok := x.GetEmptyType().(*FieldConstraints_MapConstraints_Empty); ok {
		return x.Empty
	}
	return false
}

func (x *FieldConstraints_MapConstraints) GetNotEmpty() bool {
	if x, ok := x.GetEmptyType().(*FieldConstraints_MapConstraints_NotEmpty); ok {
		return x.NotEmpty
	}
	return false
}

func (x *FieldConstraints_MapConstraints) GetLenGte() uint32 {
	if x != nil {
		return x.LenGte
	}
	return 0
}

func (x *FieldConstraints_MapConstraints) GetLenLte() uint32 {
	if x != nil {
		return x.LenLte
	}
	return 0
}

func (x *FieldConstraints_MapConstraints) GetLenEq() uint32 {
	if x != nil {
		return x.LenEq
	}
	return 0
}

func (x *FieldConstraints_MapConstraints) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FieldConstraints_MapConstraints) GetLevel() Level {
	if x != nil {
		return x.Level
	}
	return Level_LEVEL_UNSPECIFIED
}

func (x *FieldConstraints_MapConstraints) GetKeys() *FieldConstraints {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *FieldConstraints_MapConstraints) GetValues() *FieldConstraints {
	if x != nil {
		return x.Values
	}
	return nil
}

type isFieldConstraints_MapConstraints_EmptyType interface {
	isFieldConstraints_MapConstraints_EmptyType()
}

type FieldConstraints_MapConstraints_Empty struct {
	Empty bool `protobuf:"varint,1,opt,name=empty,proto3,oneof"`
}

type FieldConstraints_MapConstraints_NotEmpty struct {
	NotEmpty bool `protobuf:"varint,2,opt,name=not_empty,json=notEmpty,proto3,oneof"`
}

func (*FieldConstraints_MapConstraints_Empty) isFieldConstraints_MapConstraints_EmptyType() {}

func (*FieldConstraints_MapConstraints_NotEmpty) isFieldConstraints_MapConstraints_EmptyType() {}

type FieldConstraints_EnumConstraints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recognized bool     `protobuf:"varint,1,opt,name=recognized,proto3" json:"recognized,omitempty"`
	In         []uint32 `protobuf:"varint,2,rep,packed,name=in,proto3" json:"in,omitempty"`
	NotIn      []uint32 `protobuf:"varint,3,rep,packed,name=not_in,json=notIn,proto3" json:"not_in,omitempty"`
	Eq         uint32   `protobuf:"varint,4,opt,name=eq,proto3" json:"eq,omitempty"`
	Msg        string   `protobuf:"bytes,8,opt,name=msg,proto3" json:"msg,omitempty"`
	Level      Level    `protobuf:"varint,9,opt,name=level,proto3,enum=valid.Level" json:"level,omitempty"`
}

func (x *FieldConstraints_EnumConstraints) Reset() {
	*x = FieldConstraints_EnumConstraints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valid_field_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldConstraints_EnumConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldConstraints_EnumConstraints) ProtoMessage() {}

func (x *FieldConstraints_EnumConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_valid_field_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldConstraints_EnumConstraints.ProtoReflect.Descriptor instead.
func (*FieldConstraints_EnumConstraints) Descriptor() ([]byte, []int) {
	return file_valid_field_proto_rawDescGZIP(), []int{0, 9}
}

func (x *FieldConstraints_EnumConstraints) GetRecognized() bool {
	if x != nil {
		return x.Recognized
	}
	return false
}

func (x *FieldConstraints_EnumConstraints) GetIn() []uint32 {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *FieldConstraints_EnumConstraints) GetNotIn() []uint32 {
	if x != nil {
		return x.NotIn
	}
	return nil
}

func (x *FieldConstraints_EnumConstraints) GetEq() uint32 {
	if x != nil {
		return x.Eq
	}
	return 0
}

func (x *FieldConstraints_EnumConstraints) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FieldConstraints_EnumConstraints) GetLevel() Level {
	if x != nil {
		return x.Level
	}
	return Level_LEVEL_UNSPECIFIED
}

var file_valid_field_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.FieldOptions)(nil),
		ExtensionType: (*FieldConstraints)(nil),
		Field:         50000,
		Name:          "valid.field",
		Tag:           "bytes,50000,opt,name=field",
		Filename:      "valid/field.proto",
	},
}

// Extension fields to descriptor.FieldOptions.
var (
	// optional valid.FieldConstraints field = 50000;
	E_Field = &file_valid_field_proto_extTypes[0]
)

var File_valid_field_proto protoreflect.FileDescriptor

var file_valid_field_proto_rawDesc = []byte{
	0x0a, 0x11, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb9, 0x15, 0x0a,
	0x10, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74,
	0x73, 0x12, 0x43, 0x0a, 0x06, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x29, 0x2e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x43,
	0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x2e, 0x44, 0x6f, 0x75, 0x62, 0x6c,
	0x65, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x48, 0x00, 0x52, 0x06,
	0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x40, 0x0a, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x2e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x2e, 0x46,
	0x6c, 0x6f, 0x61, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x48,
	0x00, 0x52, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x40, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x33,
	0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x2e,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73,
	0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74,
	0x73, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x40, 0x0a, 0x05, 0x69, 0x6e,
	0x74, 0x36, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x74, 0x73, 0x2e, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x74, 0x73, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x3d, 0x0a, 0x04,
	0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x74, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x74, 0x73, 0x48, 0x00, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x12, 0x43, 0x0a, 0x06, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61,
	0x69, 0x6e, 0x74, 0x73, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x73, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x12, 0x40, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x28, 0x2e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x43, 0x6f, 0x6e,
	0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x43, 0x6f,
	0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x48, 0x00, 0x52, 0x05, 0x62, 0x79, 0x74,
	0x65, 0x73, 0x12, 0x49, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x10,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x2e, 0x52, 0x65,
	0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74,
	0x73, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x3a, 0x0a,
	0x03, 0x6d, 0x61, 0x70, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x74, 0x73, 0x2e, 0x4d, 0x61, 0x70, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x74, 0x73, 0x48, 0x00, 0x52, 0x03, 0x6d, 0x61, 0x70, 0x12, 0x3d, 0x0a, 0x04, 0x65, 0x6e, 0x75,
	0x6d, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x2e,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73,
	0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73,
	0x48, 0x00, 0x52, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x1a, 0xb5, 0x01, 0x0a, 0x11, 0x44, 0x6f, 0x75,
	0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x12,
	0x0a, 0x03, 0x67, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x03, 0x67,
	0x74, 0x65, 0x12, 0x10, 0x0a, 0x02, 0x67, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00,
	0x52, 0x02, 0x67, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x6c, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x48, 0x01, 0x52, 0x03, 0x6c, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x02, 0x6c, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x01, 0x48, 0x01, 0x52, 0x02, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x70,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x65, 0x70, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x22,
	0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x05, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x61, 0x78,
	0x1a, 0xb4, 0x01, 0x0a, 0x10, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x03, 0x67, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x01, 0x48, 0x00, 0x52, 0x03, 0x67, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x02, 0x67, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x02, 0x67, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x6c,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x48, 0x01, 0x52, 0x03, 0x6c, 0x74, 0x65, 0x12,
	0x10, 0x0a, 0x02, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x48, 0x01, 0x52, 0x02, 0x6c,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x70, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03,
	0x65, 0x70, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x22, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x2e, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x69, 0x6e,
	0x42, 0x05, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x1a, 0xd9, 0x01, 0x0a, 0x10, 0x49, 0x6e, 0x74, 0x33,
	0x32, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x03,
	0x67, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x03, 0x67, 0x74, 0x65,
	0x12, 0x10, 0x0a, 0x02, 0x67, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x02,
	0x67, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x6c, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48,
	0x01, 0x52, 0x03, 0x6c, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x02, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x48, 0x01, 0x52, 0x02, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x6e, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x02, 0x69, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x6e, 0x6f, 0x74, 0x5f,
	0x69, 0x6e, 0x18, 0x06, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x6e, 0x6f, 0x74, 0x49, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x65, 0x71, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x12, 0x22, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0c, 0x2e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x42, 0x05, 0x0a, 0x03,
	0x6d, 0x61, 0x78, 0x1a, 0xd9, 0x01, 0x0a, 0x10, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x43, 0x6f, 0x6e,
	0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x03, 0x67, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x03, 0x67, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x02,
	0x67, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x02, 0x67, 0x74, 0x12, 0x12,
	0x0a, 0x03, 0x6c, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x01, 0x52, 0x03, 0x6c,
	0x74, 0x65, 0x12, 0x10, 0x0a, 0x02, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x48, 0x01,
	0x52, 0x02, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x6e, 0x6f, 0x74, 0x5f, 0x69, 0x6e, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x03, 0x52, 0x05, 0x6e, 0x6f, 0x74, 0x49, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x65,
	0x71, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x22, 0x0a,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x1a,
	0x21, 0x0a, 0x0f, 0x42, 0x6f, 0x6f, 0x6c, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x74, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02,
	0x65, 0x71, 0x1a, 0x81, 0x02, 0x0a, 0x11, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e,
	0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x1d, 0x0a, 0x09, 0x6e, 0x6f, 0x74, 0x5f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x08, 0x6e, 0x6f, 0x74, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x15, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x5f, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x6c, 0x65, 0x6e, 0x45, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x65, 0x6e, 0x5f, 0x67, 0x74,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x47, 0x74, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x6c, 0x65, 0x6e, 0x5f, 0x6c, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x6c, 0x65, 0x6e, 0x4c, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x65, 0x71, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x74, 0x74,
	0x65, 0x72, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65,
	0x72, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x12, 0x22, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x2e, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x42, 0x0c, 0x0a, 0x0a, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x1a, 0xd6, 0x01, 0x0a, 0x10, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x05, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x05, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x1d, 0x0a, 0x09, 0x6e, 0x6f, 0x74, 0x5f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x08, 0x6e, 0x6f, 0x74, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x15, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x5f, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x6e, 0x45, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x65, 0x6e,
	0x5f, 0x67, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x47,
	0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x65, 0x6e, 0x5f, 0x6c, 0x74, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x4c, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x22, 0x0a,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x42, 0x0c, 0x0a, 0x0a, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x1a,
	0x88, 0x02, 0x0a, 0x13, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x73,
	0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x1d, 0x0a, 0x09, 0x6e, 0x6f, 0x74, 0x5f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x48, 0x00, 0x52, 0x08, 0x6e, 0x6f, 0x74, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x17,
	0x0a, 0x07, 0x6c, 0x65, 0x6e, 0x5f, 0x67, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x6c, 0x65, 0x6e, 0x47, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x65, 0x6e, 0x5f, 0x6c,
	0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x4c, 0x74, 0x65,
	0x12, 0x15, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x5f, 0x65, 0x71, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x6c, 0x65, 0x6e, 0x45, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x22, 0x0a, 0x05, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x2d, 0x0a,
	0x05, 0x65, 0x6c, 0x65, 0x6d, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x05, 0x65, 0x6c, 0x65, 0x6d, 0x73, 0x42, 0x0c, 0x0a, 0x0a,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x1a, 0xb2, 0x02, 0x0a, 0x0e, 0x4d,
	0x61, 0x70, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x0a,
	0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x05,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x1d, 0x0a, 0x09, 0x6e, 0x6f, 0x74, 0x5f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x08, 0x6e, 0x6f, 0x74, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x65, 0x6e, 0x5f, 0x67, 0x74, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x47, 0x74, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x6c, 0x65, 0x6e, 0x5f, 0x6c, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x6c, 0x65, 0x6e, 0x4c, 0x74, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x5f, 0x65, 0x71,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x6e, 0x45, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12,
	0x22, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c,
	0x2e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x12, 0x2b, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x43,
	0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73,
	0x12, 0x2f, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x43, 0x6f,
	0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x42, 0x0c, 0x0a, 0x0a, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x1a,
	0x9e, 0x01, 0x0a, 0x0f, 0x45, 0x6e, 0x75, 0x6d, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x74, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x7a, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69,
	0x7a, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x6e, 0x6f, 0x74, 0x5f, 0x69, 0x6e, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0d, 0x52, 0x05, 0x6e, 0x6f, 0x74, 0x49, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x65, 0x71,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x22, 0x0a, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x60, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x12, 0x15, 0x0a, 0x11, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4c, 0x45, 0x56, 0x45,
	0x4c, 0x5f, 0x44, 0x45, 0x42, 0x55, 0x47, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x4c, 0x45, 0x56,
	0x45, 0x4c, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4c, 0x45, 0x56,
	0x45, 0x4c, 0x5f, 0x57, 0x41, 0x52, 0x4e, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x4c, 0x45, 0x56,
	0x45, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x04, 0x3a, 0x4e, 0x0a, 0x05, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0xd0, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x74, 0x73, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x69, 0x74, 0x63, 0x64, 0x72, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_valid_field_proto_rawDescOnce sync.Once
	file_valid_field_proto_rawDescData = file_valid_field_proto_rawDesc
)

func file_valid_field_proto_rawDescGZIP() []byte {
	file_valid_field_proto_rawDescOnce.Do(func() {
		file_valid_field_proto_rawDescData = protoimpl.X.CompressGZIP(file_valid_field_proto_rawDescData)
	})
	return file_valid_field_proto_rawDescData
}

var file_valid_field_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_valid_field_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_valid_field_proto_goTypes = []interface{}{
	(Level)(0),               // 0: valid.Level
	(*FieldConstraints)(nil), // 1: valid.FieldConstraints
	(*FieldConstraints_DoubleConstraints)(nil),   // 2: valid.FieldConstraints.DoubleConstraints
	(*FieldConstraints_FloatConstraints)(nil),    // 3: valid.FieldConstraints.FloatConstraints
	(*FieldConstraints_Int32Constraints)(nil),    // 4: valid.FieldConstraints.Int32Constraints
	(*FieldConstraints_Int64Constraints)(nil),    // 5: valid.FieldConstraints.Int64Constraints
	(*FieldConstraints_BoolConstraints)(nil),     // 6: valid.FieldConstraints.BoolConstraints
	(*FieldConstraints_StringConstraints)(nil),   // 7: valid.FieldConstraints.StringConstraints
	(*FieldConstraints_BytesConstraints)(nil),    // 8: valid.FieldConstraints.BytesConstraints
	(*FieldConstraints_RepeatedConstraints)(nil), // 9: valid.FieldConstraints.RepeatedConstraints
	(*FieldConstraints_MapConstraints)(nil),      // 10: valid.FieldConstraints.MapConstraints
	(*FieldConstraints_EnumConstraints)(nil),     // 11: valid.FieldConstraints.EnumConstraints
	(*descriptor.FieldOptions)(nil),              // 12: google.protobuf.FieldOptions
}
var file_valid_field_proto_depIdxs = []int32{
	2,  // 0: valid.FieldConstraints.double:type_name -> valid.FieldConstraints.DoubleConstraints
	3,  // 1: valid.FieldConstraints.float:type_name -> valid.FieldConstraints.FloatConstraints
	4,  // 2: valid.FieldConstraints.int32:type_name -> valid.FieldConstraints.Int32Constraints
	5,  // 3: valid.FieldConstraints.int64:type_name -> valid.FieldConstraints.Int64Constraints
	6,  // 4: valid.FieldConstraints.bool:type_name -> valid.FieldConstraints.BoolConstraints
	7,  // 5: valid.FieldConstraints.string:type_name -> valid.FieldConstraints.StringConstraints
	8,  // 6: valid.FieldConstraints.bytes:type_name -> valid.FieldConstraints.BytesConstraints
	9,  // 7: valid.FieldConstraints.repeated:type_name -> valid.FieldConstraints.RepeatedConstraints
	10, // 8: valid.FieldConstraints.map:type_name -> valid.FieldConstraints.MapConstraints
	11, // 9: valid.FieldConstraints.enum:type_name -> valid.FieldConstraints.EnumConstraints
	0,  // 10: valid.FieldConstraints.DoubleConstraints.level:type_name -> valid.Level
	0,  // 11: valid.FieldConstraints.FloatConstraints.level:type_name -> valid.Level
	0,  // 12: valid.FieldConstraints.Int32Constraints.level:type_name -> valid.Level
	0,  // 13: valid.FieldConstraints.Int64Constraints.level:type_name -> valid.Level
	0,  // 14: valid.FieldConstraints.StringConstraints.level:type_name -> valid.Level
	0,  // 15: valid.FieldConstraints.BytesConstraints.level:type_name -> valid.Level
	0,  // 16: valid.FieldConstraints.RepeatedConstraints.level:type_name -> valid.Level
	1,  // 17: valid.FieldConstraints.RepeatedConstraints.elems:type_name -> valid.FieldConstraints
	0,  // 18: valid.FieldConstraints.MapConstraints.level:type_name -> valid.Level
	1,  // 19: valid.FieldConstraints.MapConstraints.keys:type_name -> valid.FieldConstraints
	1,  // 20: valid.FieldConstraints.MapConstraints.values:type_name -> valid.FieldConstraints
	0,  // 21: valid.FieldConstraints.EnumConstraints.level:type_name -> valid.Level
	12, // 22: valid.field:extendee -> google.protobuf.FieldOptions
	1,  // 23: valid.field:type_name -> valid.FieldConstraints
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	23, // [23:24] is the sub-list for extension type_name
	22, // [22:23] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_valid_field_proto_init() }
func file_valid_field_proto_init() {
	if File_valid_field_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_valid_field_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldConstraints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valid_field_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldConstraints_DoubleConstraints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valid_field_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldConstraints_FloatConstraints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valid_field_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldConstraints_Int32Constraints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valid_field_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldConstraints_Int64Constraints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valid_field_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldConstraints_BoolConstraints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valid_field_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldConstraints_StringConstraints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valid_field_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldConstraints_BytesConstraints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valid_field_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldConstraints_RepeatedConstraints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valid_field_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldConstraints_MapConstraints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valid_field_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldConstraints_EnumConstraints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_valid_field_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*FieldConstraints_Double)(nil),
		(*FieldConstraints_Float)(nil),
		(*FieldConstraints_Int32)(nil),
		(*FieldConstraints_Int64)(nil),
		(*FieldConstraints_Bool)(nil),
		(*FieldConstraints_String_)(nil),
		(*FieldConstraints_Bytes)(nil),
		(*FieldConstraints_Repeated)(nil),
		(*FieldConstraints_Map)(nil),
		(*FieldConstraints_Enum)(nil),
	}
	file_valid_field_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*FieldConstraints_DoubleConstraints_Gte)(nil),
		(*FieldConstraints_DoubleConstraints_Gt)(nil),
		(*FieldConstraints_DoubleConstraints_Lte)(nil),
		(*FieldConstraints_DoubleConstraints_Lt)(nil),
	}
	file_valid_field_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*FieldConstraints_FloatConstraints_Gte)(nil),
		(*FieldConstraints_FloatConstraints_Gt)(nil),
		(*FieldConstraints_FloatConstraints_Lte)(nil),
		(*FieldConstraints_FloatConstraints_Lt)(nil),
	}
	file_valid_field_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*FieldConstraints_Int32Constraints_Gte)(nil),
		(*FieldConstraints_Int32Constraints_Gt)(nil),
		(*FieldConstraints_Int32Constraints_Lte)(nil),
		(*FieldConstraints_Int32Constraints_Lt)(nil),
	}
	file_valid_field_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*FieldConstraints_Int64Constraints_Gte)(nil),
		(*FieldConstraints_Int64Constraints_Gt)(nil),
		(*FieldConstraints_Int64Constraints_Lte)(nil),
		(*FieldConstraints_Int64Constraints_Lt)(nil),
	}
	file_valid_field_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*FieldConstraints_StringConstraints_Empty)(nil),
		(*FieldConstraints_StringConstraints_NotEmpty)(nil),
	}
	file_valid_field_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*FieldConstraints_BytesConstraints_Empty)(nil),
		(*FieldConstraints_BytesConstraints_NotEmpty)(nil),
	}
	file_valid_field_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*FieldConstraints_RepeatedConstraints_Empty)(nil),
		(*FieldConstraints_RepeatedConstraints_NotEmpty)(nil),
	}
	file_valid_field_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*FieldConstraints_MapConstraints_Empty)(nil),
		(*FieldConstraints_MapConstraints_NotEmpty)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_valid_field_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_valid_field_proto_goTypes,
		DependencyIndexes: file_valid_field_proto_depIdxs,
		EnumInfos:         file_valid_field_proto_enumTypes,
		MessageInfos:      file_valid_field_proto_msgTypes,
		ExtensionInfos:    file_valid_field_proto_extTypes,
	}.Build()
	File_valid_field_proto = out.File
	file_valid_field_proto_rawDesc = nil
	file_valid_field_proto_goTypes = nil
	file_valid_field_proto_depIdxs = nil
}
