// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.11.3
// source: valid/level.proto

package valid

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Level int32

const (
	Level_LEVEL_UNSPECIFIED Level = 0
	Level_LEVEL_DEBUG       Level = 1
	Level_LEVEL_INFO        Level = 2
	Level_LEVEL_WARN        Level = 3
	Level_LEVEL_ERROR       Level = 4
)

// Enum value maps for Level.
var (
	Level_name = map[int32]string{
		0: "LEVEL_UNSPECIFIED",
		1: "LEVEL_DEBUG",
		2: "LEVEL_INFO",
		3: "LEVEL_WARN",
		4: "LEVEL_ERROR",
	}
	Level_value = map[string]int32{
		"LEVEL_UNSPECIFIED": 0,
		"LEVEL_DEBUG":       1,
		"LEVEL_INFO":        2,
		"LEVEL_WARN":        3,
		"LEVEL_ERROR":       4,
	}
)

func (x Level) Enum() *Level {
	p := new(Level)
	*p = x
	return p
}

func (x Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Level) Descriptor() protoreflect.EnumDescriptor {
	return file_valid_level_proto_enumTypes[0].Descriptor()
}

func (Level) Type() protoreflect.EnumType {
	return &file_valid_level_proto_enumTypes[0]
}

func (x Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Level.Descriptor instead.
func (Level) EnumDescriptor() ([]byte, []int) {
	return file_valid_level_proto_rawDescGZIP(), []int{0}
}

var File_valid_level_proto protoreflect.FileDescriptor

var file_valid_level_proto_rawDesc = []byte{
	0x0a, 0x11, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x2f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x2a, 0x60, 0x0a, 0x05, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x12, 0x15, 0x0a, 0x11, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4c, 0x45,
	0x56, 0x45, 0x4c, 0x5f, 0x44, 0x45, 0x42, 0x55, 0x47, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x4c,
	0x45, 0x56, 0x45, 0x4c, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4c,
	0x45, 0x56, 0x45, 0x4c, 0x5f, 0x57, 0x41, 0x52, 0x4e, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x4c,
	0x45, 0x56, 0x45, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x04, 0x42, 0x24, 0x5a, 0x22,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x69, 0x74, 0x63, 0x64,
	0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x2f, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_valid_level_proto_rawDescOnce sync.Once
	file_valid_level_proto_rawDescData = file_valid_level_proto_rawDesc
)

func file_valid_level_proto_rawDescGZIP() []byte {
	file_valid_level_proto_rawDescOnce.Do(func() {
		file_valid_level_proto_rawDescData = protoimpl.X.CompressGZIP(file_valid_level_proto_rawDescData)
	})
	return file_valid_level_proto_rawDescData
}

var file_valid_level_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_valid_level_proto_goTypes = []interface{}{
	(Level)(0), // 0: valid.Level
}
var file_valid_level_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_valid_level_proto_init() }
func file_valid_level_proto_init() {
	if File_valid_level_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_valid_level_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_valid_level_proto_goTypes,
		DependencyIndexes: file_valid_level_proto_depIdxs,
		EnumInfos:         file_valid_level_proto_enumTypes,
	}.Build()
	File_valid_level_proto = out.File
	file_valid_level_proto_rawDesc = nil
	file_valid_level_proto_goTypes = nil
	file_valid_level_proto_depIdxs = nil
}
